### ISSUE TITLE
Delegate method not called.

### ISSUE THREAD

**Issue by euroboy** [XuYanci/GLViewPagerController#10]
Hi. I'm unable to adjust tabs width, and I figured out that method `- (CGFloat)viewPager:(GLViewPagerViewController *)viewPager widthForTabIndex:(NSUInteger)index` is never called. 
I'm setting delegate and datasource in `viewDidLoad`:

```
self.dataSource = self;
self.delegate = self;
```

How can I solve this?

**Comment by XuYanci** [comment]
Please see the demo .
