### ISSUE TITLE
标签代理方法中创建复杂视图会崩溃

### ISSUE THREAD

**Issue by wanderingsoulsdc** [XuYanci/GLViewPagerController#11]
- (UIView *)viewPager:(GLViewPagerViewController *)viewPager
      viewForTabIndex:(NSUInteger)index {
    UILabel *label = [[UILabel alloc]initWithFrame:v.bounds];
    label.text = [self.tagTitles objectAtIndex:index];
    label.font = [UIFont systemFontOfSize:16.0];
    /** 默认紫色 */
    label.textColor =[UIColor colorWithRed:0.5
                                     green:0.0
                                      blue:0.5
                                     alpha:1.0];
 
    label.textAlignment = NSTextAlignmentCenter;
#if 0
    label.transform = CGAffineTransformScale(CGAffineTransformIdentity, 0.9, 0.9);
#endif
    UIView *v = [[UIView alloc] init];
    [v addSubview:label];
    return v; //此处如果只返回label 不会崩溃
}

**Comment by XuYanci** [comment]
![image](https://user-images.githubusercontent.com/10784657/44295630-9968f780-a2df-11e8-97fe-ce75c4ad9452.png)
