### ISSUE TITLE
Tabs from Right to left

### ISSUE THREAD

**Issue by malqadi88** [XuYanci/GLViewPagerController#2]
hi 
can you support tabs from right to left>

I hope do this.

Thanks

**Comment by XuYanci** [comment]
OK  i will see it later , thanks for your advice .

**Comment by XuYanci** [comment]
can u describe more detail about this effect.

**Comment by malqadi88** [comment]
I need to start first tabs from Right 

like this 
...... page three , page two , page One

can you make it  ?
Thanks

**Comment by malqadi88** [comment]
to support arabic language 

OK , i will add an property for layout converse ...

**Comment by XuYanci** [comment]
Ok . I will resolve later .
